### ISSUE TITLE
Update Bootstrap to v3.3.4

### ISSUE THREAD

**Issue by cvrebert** [LogicSoftInd/LSQ#1]
This is currently using v3.3.2.

**Comment by shrayasr** [comment]
Thanks for the issue :smile: :+1:

Is there any compelling reason to do this though? Can't we just wait for the next release with more features instead of moving minor releases?

**Comment by Fajkowsky** [comment]
If you are using some elements that are are being used, you should upgrade. There are improvements and bug fixes so check in change log if there are some fixes in elements that being used by LSQ.

**Comment by shrayasr** [comment]
On first glance, it doesn't look like it. However I'll give this a more detailed read just to be sure.
