### ISSUE TITLE
I went wild with this...

### ISSUE THREAD

**Issue by froi** [LogicSoftInd/LSQ#6]
I kinda went wild with the project and made considerable changes that still keep the spirit of the app. I would love for you guys to take a look at it and see if you would like a pull request.

What I did:
- Added Flask-Login
- Added a sort of comment system.
- Added Mongokit ORM for mongodb.
- Cosmetic changes to templates and code refactor.

I haven't submitted a pull request because of the size of the changes. [Here's some screenshots](http://imgur.com/a/knmao#0) and [here's the repo](https://github.com/froi/morsel). I hope you guys like it.

**Comment by shrayasr** [comment]
WOAAAH :scream: This is insane. 

Firstly, so sorry about the late reply. I will take a look at all this in leisure and get back to you. This is really amazing :smile:

**Comment by froi** [comment]
No worries @shrayasr 

Let me know if you want a pull request. Cheers. :)
